language: minimal

# Install Hugo
install:
  - url=https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_extended_0.68.3_Linux-64bit.deb
  - echo $url
  - curl -OLkSs $url
  - sudo dpkg -i hugo*.deb

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PAGES_TOKEN
  on:
    branch: master
  local_dir: public
  repo: olzhy/olzhy.github.io
  fqdn: olzhy.github.io
  target_branch: master
  email: olzhy@qq.com
  name: olzhy
