############################ Default configuration #########################
baseURL = "https://olzhy.github.io/"
languageCode = "zh-cn"
# site title 
title = "Hugo"
# theme
theme = "northendlab-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "5"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

[services.rss]
    limit = 15

# Author’s information
[author]
    # Name
    name = "磊磊落落"
    # Email
    email = "leileiluoluo@leileiluoluo.com"
    # Motto or introduction
    motto = "磊磊落落的博客"

[outputs]
home = ["HTML", "AMP", "RSS", "JSON", "SectionsAtom", "SectionsRSS"]

# MIME type of Atom
[mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

# Custom Atom template of MemE
[outputFormats.SectionsAtom]
    mediaType = "application/atom+xml"
    baseName = "atom"

# Custom RSS template of MemE
[outputFormats.SectionsRSS]
    mediaType = "application/rss+xml"
    baseName = "rss"

########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
link = "css/bootstrap.min.css"
[[params.plugins.css]]
link = "css/themify-icons.css"
[[params.plugins.css]]
link = "css/larry-custom.css"

# js plugins
[[params.plugins.js]]
link = "js/jquery.min.js"
[[params.plugins.js]]
link = "js/bootstrap.min.js"
[[params.plugins.js]]
link = "js/fuse.min.js"
[[params.plugins.js]]
link = "js/mark.js"
[[params.plugins.js]]
link = "js/search.js"

########################### Navigation ###################################

# main menu
[[menu.main]]
URL = "/categories/随笔/"
name = "随笔"
weight = 1

[[menu.main]]
URL = "/categories/读书/"
name = "读书"
weight = 2

[[menu.main]]
URL = "/categories/观影/"
name = "观影"
weight = 3

[[menu.main]]
URL = "/categories/练字/"
name = "练字"
weight = 4

[[menu.main]]
URL = "/categories/计算机/"
name = "计算机"
weight = 5

# footer menu
[[menu.footer]]
URL = "/leetcode-golang-implementations"
name = "LeetCode"
weight = 1

[[menu.footer]]
URL = "/about"
name = "关于本站"
weight = 2

[[menu.footer]]
URL = "/links"
name = "友情链接"
weight = 3


######################### Default Parameters ###########################
[params]
# home
home = ""
# logo
logo = "static/images/self/logo.svg"
# meta data
author = "磊磊落落"
keywords = ["Golang", "Python", "云原生", "机器学习", "LeetCode", "技术博客"]
description = "磊磊落落，是本人用于记录内心波澜，分享读书感想，思考人生哲学，关注社会百态，梳理计算机专业知识的纯原创站点。"
# google tag manager
google_tag_manager = "" # your id
# google analitycs ID
google_analitycs_id = "" # your id
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# copyright
copyright = "Thanks [Hugo](https://gohugo.io/) & [NorthendLab](https://github.com/themefisher/northendlab-hugo) | [晋ICP备08100400号-4](http://beian.miit.gov.cn/state/outPortal/loginPortal.action) | [leileiluoluo.com](https://www.leileiluoluo.com/)&copy;2021"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# search
[params.search]
enable = true

####################### banner #######################################
[params.banner]
enable = true
bgImage = "static/images/site/henry-small.jpg" # background site https://unsplash.com/s/photos/blog-background
title = "人心惟危 道心惟微 惟精惟一 允执厥中"
image = ""


######################## call to action ###############################
[params.cta]
enable = false
image = "static/images/site/jinshu.png"
title = "“大丈夫行事，当磊磊落落，如日月皎然。”——《晋书》"
description = "磊磊落落：IT从业者，生活记录者。博客名称取自《晋书》，勉励本人光明磊落做人做事。该博客是本人用于记录内心波澜，分享读书感想，思考人生哲学，关注社会百态，梳理计算机专业知识的纯原创站点。"
[params.cta.button]
enable = false
label = "Visit Here"
link = "https://gethugothemes.com/shop/"

# reward
[params.reward]
enable = true

# comment
[params.comment]
enable = false

# baidu tongji
[params.baidu_tongji]
enable = true


############################# Social Site ##########################
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "https://github.com/olzhy"
[[params.social]]
icon = "ti-rss" # themify icon pack https://themify.me/themify-icons
link = "/index.xml"
[[params.social]]
icon = "ti-email" # themify icon pack https://themify.me/themify-icons
link = "mailto:leileiluoluo@leileiluoluo.com"
