name: Github Actions for Hugo Deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0
      # - name: Publish Site
        # uses: chabad360/hugo-gh-pages@master
        # with:
        #   githubToken: ${{ secrets.ENPUBLIC_GITHUB_TOKEN }}
        #   cname: olzhy.github.io
        #   branch: master
        #   repo: olzhy/olzhy.github.io
        #   hugoVersion: extended_0.81.0
        #   args: --minify
        #   siteDir: /github/workspace
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          extended: true
      - name: Build
        run: |
          hugo --minify
      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: './public'
          target: '/tmp/'
      - name: Start Service
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            find /tmp/public -type f | xargs sed -i "s#https://olzhy.github.io#https://leileiluoluo.com#g"
            cp -rf /tmp/public/* /usr/share/nginx/html
            service nginx reload
