name: Github Actions for Hugo Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0
      - name: Run shell
        run: |
          ls -lht
          find . -type f | xargs sed -i "s#https://olzhy.github.io#https://leileiluoluo.com#g"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.123.7"
          extended: true
      - name: Hugo Build
        run: |
          hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          emptyCommits: false
        env:
          github_token: ${{ secrets.ENPUBLIC_GITHUB_TOKEN }}
          external_repository: olzhy/olzhy.github.io
          publish_branch: master
          publish_dir: ./public
          allow_empty_commit: true
      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./public"
          target: "/tmp/leileiluoluo/"
      - name: Start Service
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            mkdir -p /usr/share/nginx/html/leileiluoluo
            cp -rf /tmp/leileiluoluo/public/* /usr/share/nginx/html/leileiluoluo
            service nginx reload

  sync:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:olzhy/olzhy.github.io.git"
          destination-repo: "git@gitee.com:olzhy/olzhy.github.io.git"
