name: Github Actions for Hugo Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.123.7"
          extended: true
      - name: Hugo Build
        run: |
          hugo --minify
      - name: Run shell
        run: |
          ls -lht
          find . -type f | xargs sed -i "s#https://leileiluoluo.github.io#https://leileiluoluo.com#g"
      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./public"
          target: "/tmp/leileiluoluo/"
      - name: Start Service
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            mkdir -p /usr/share/nginx/html/leileiluoluo
            cp -rf /tmp/leileiluoluo/public/* /usr/share/nginx/html/leileiluoluo
            service nginx reload
