name: Github Actions for Hugo Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.ENPUBLIC_GITHUB_TOKEN }}
          # Remember to set this as a secret (i.e. secrets.PERSONAL_TOKEN).
          # Don't forget to set the secret value in the project settings.
          cname: olzhy.github.io # Or anything else
          # Use if you have a custom domain for your site.
          branch: master # Or anything else
          # Use if your site is not hosted on the gh-pages branch.
          repo: olzhy/olzhy.github.io
          # Use if you're pushing to a different repo.
          # Dont add ".git" to the end of the URL (youl'll get 404s).
          hugoVersion: extended_0.81.0
          # Use if your site requires a specific version of Hugo.
          # Append "extended_" to the begining to use Hugo Extended.
          args: --minify
          # Use if you want to pass some custom arguments to Hugo.
          siteDir: /github/workspace/public
          # Use this if your site isn't in the root of your repo.
          # The root of your repo can be found at /github/workspace
      - name: Deploy to enpublic
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.81.0
          HUGO_EXTENDED: true
          TARGET_REPO: olzhy/olzhy.github.io
          TARGET_BRANCH: master
          TOKEN: ${{ secrets.ENPUBLIC_GITHUB_TOKEN }}
          CNAME: olzhy.github.io
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/gitee-mirror-action@v0.01
        with:
          src: github/olzhy
          dst: gitee/olzhy
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
