name: Github Actions for Hugo Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0
      - name: Run shell
        run: |
             ls -lht
             find . -type f | xargs sed -i "s#https://olzhy.github.io#https://leileiluoluo.com#g"
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.ENPUBLIC_GITHUB_TOKEN }}
          cname: leileiluoluo.com
          branch: master
          repo: olzhy/olzhy.github.io
          hugoVersion: extended_0.81.0
          args: --minify
          siteDir: /github/workspace
  sync:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:olzhy/olzhy.github.io.git"
          destination-repo: "git@gitee.com:olzhy/olzhy.github.io.git"
