name: Github Actions for Hugo Deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.ENPUBLIC_GITHUB_TOKEN }}
          cname: olzhy.github.io
          branch: master
          repo: olzhy/olzhy.github.io
          hugoVersion: extended_0.81.0
          args: --minify
          siteDir: /github/workspace
  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: '/github/workspace/'
          target: '/tmp/'
      # - name: Start Service
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     host: ${{ secrets.HOST }}
      #     port: ${{ secrets.PORT }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     script: |
      #       cd /usr/app/
      #       source /etc/profile
      #       ps -ef | grep java | grep -v grep | awk '{print $2}' | xargs kill -9
      #       rm /usr/app/old/boyouquan-1.0-SNAPSHOT.jar
      #       mv /usr/app/new/target/boyouquan-1.0-SNAPSHOT.jar /usr/app/old/
      #       export DATABASE_URL=$DATABASE_URL
      #       export DATABASE_USER=$DATABASE_USER
      #       export DATABASE_PASSWORD=$DATABASE_PASSWORD
      #       nohup java -jar /usr/app/old/boyouquan-1.0-SNAPSHOT.jar > /tmp/server.log 2>&1 &
      #       sleep 1
      #       while ! grep -m1 'Started BoYouQuanWebApplication' < /tmp/server.log; do
      #         sleep 1
      #       done
      #       ps -ef | grep java | grep -v grep
      #       echo "Server started!"
